extensions:
  - quiz
  - short-questions
  - long-questions
  - progress-check
  - slides
  - counter
  - videos
  - notify-old-page
  - auth

config:
  short-questions:
    text: "Check"
  counter:
    - question
    - tip
  auth:
    url: http://localhost:8000/login
    watch-urls: ".*auth.*"
  report: 
    url: http://localhost:8000/api/offerings/1/exercises/
